# Generated by Django 4.2.7 on 2024-01-09 11:52

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_title', models.CharField(max_length=100)),
                ('enquiry_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
