# Generated by Django 4.2.7 on 2024-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_image',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='news/'),
        ),
    ]
